"""Confidence intervals and paired significance tests for the cited-paper ranking benchmark.

Reads the per-query rankings in research/eval_dataset/week3/rankings_*.json
(100 queries, RANDOM_SEED = 42 subset of the 174-query benchmark) and writes:

  research/stats/results.md   - tables used in the README
  research/stats/mrr_ci.svg   - MRR with 95% bootstrap confidence intervals

Usage (from the repository root):
    python research/stats/significance.py
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
matplotlib.rcParams["svg.fonttype"] = "none"  # keep text as text: small, diff-friendly SVG
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from scipy.stats import wilcoxon  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
RANKINGS = ROOT / "research" / "eval_dataset" / "week3"
OUT = Path(__file__).resolve().parent

# file suffix -> display name. Only methods reported in the final report.
METHODS = {
    "llama": "Llama 3.2 3B reranker (listwise, full pool)",
    "qwen→llama": "Two-stage: Qwen3 → Llama 3.2 3B",
    "qwen": "Qwen3 embedding",
    "qwen+minilm": "Qwen3 + MiniLM (fusion)",
    "minilm": "MiniLM (all-MiniLM-L6-v2)",
    "llama+minilm": "Llama + MiniLM (fusion)",
    "embeddinggemma": "EmbeddingGemma",
    "tfidf": "TF-IDF",
    "specter2": "SPECTER2",
    "bm25": "BM25",
}

# Pairs whose difference the README discusses.
PAIRS = [
    ("llama", "qwen"),
    ("llama", "minilm"),
    ("qwen→llama", "qwen"),
    ("llama", "qwen→llama"),
    ("qwen", "minilm"),
    ("minilm", "tfidf"),
    ("specter2", "minilm"),
    ("qwen", "bm25"),
]

N_BOOT = 10_000
SEED = 42


def load() -> tuple[dict[str, dict[str, dict]], list[str]]:
    data = {}
    for key in METHODS:
        path = RANKINGS / f"rankings_{key}.json"
        rows = json.loads(path.read_text(encoding="utf-8"))
        data[key] = {r["pi_id"]: r for r in rows}
    ids = sorted(set.intersection(*(set(v) for v in data.values())))
    return data, ids


def values(data, ids, method: str, metric: str) -> np.ndarray:
    return np.array([data[method][i][metric] for i in ids], dtype=float)


def boot_ci(x: np.ndarray, rng: np.random.Generator) -> tuple[float, float]:
    idx = rng.integers(0, len(x), size=(N_BOOT, len(x)))
    means = x[idx].mean(axis=1)
    lo, hi = np.percentile(means, [2.5, 97.5])
    return float(lo), float(hi)


def holm(pvals: list[float]) -> list[float]:
    order = np.argsort(pvals)
    m = len(pvals)
    adj = np.empty(m)
    running = 0.0
    for rank, i in enumerate(order):
        running = max(running, (m - rank) * pvals[i])
        adj[i] = min(1.0, running)
    return adj.tolist()


def main() -> None:
    rng = np.random.default_rng(SEED)
    data, ids = load()
    n = len(ids)

    rows = []
    for key, name in METHODS.items():
        rp = values(data, ids, key, "hit_rate")
        mrr = values(data, ids, key, "mrr")
        ndcg = values(data, ids, key, "ndcg")
        top1 = (mrr == 1.0).astype(float) * 100
        rows.append(
            {
                "key": key,
                "name": name,
                "rp": rp.mean(),
                "rp_ci": boot_ci(rp, rng),
                "mrr": mrr.mean(),
                "mrr_ci": boot_ci(mrr, rng),
                "ndcg": ndcg.mean(),
                "top1": top1.mean(),
            }
        )
    rows.sort(key=lambda r: -r["mrr"])

    tests = []
    for a, b in PAIRS:
        for metric in ("mrr", "hit_rate"):
            x, y = values(data, ids, a, metric), values(data, ids, b, metric)
            p = wilcoxon(x, y).pvalue if np.any(x != y) else 1.0
            tests.append((a, b, metric, x.mean() - y.mean(), p))
    adj = holm([t[4] for t in tests])

    lines = [
        f"# Benchmark statistics ({n} queries)",
        "",
        "Generated by `research/stats/significance.py`. 95% CIs: percentile bootstrap, "
        f"{N_BOOT:,} resamples, seed {SEED}.",
        "",
        "| Method | MRR [95% CI] | R-precision % [95% CI] | nDCG@n | Top-1 % |",
        "|---|---|---|---|---|",
    ]
    for r in rows:
        lines.append(
            f"| {r['name']} | {r['mrr']:.3f} [{r['mrr_ci'][0]:.3f}, {r['mrr_ci'][1]:.3f}] "
            f"| {r['rp']:.1f} [{r['rp_ci'][0]:.1f}, {r['rp_ci'][1]:.1f}] "
            f"| {r['ndcg']:.3f} | {r['top1']:.0f} |"
        )
    lines += [
        "",
        "## Paired Wilcoxon signed-rank tests (Holm-corrected across all rows)",
        "",
        "| Comparison | Metric | Mean difference | p (Holm) |",
        "|---|---|---|---|",
    ]
    for (a, b, metric, diff, _), p in zip(tests, adj):
        label = "MRR" if metric == "mrr" else "R-precision"
        lines.append(f"| {METHODS[a]} vs {METHODS[b]} | {label} | {diff:+.3f} | {p:.2g} |")
    (OUT / "results.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Figure: MRR with CIs, sorted.
    fig, ax = plt.subplots(figsize=(7.5, 4.6))
    ys = np.arange(len(rows))[::-1]
    for y, r in zip(ys, rows):
        color = "#c0392b" if r["key"] == "llama" else ("#e67e22" if r["key"] == "qwen→llama" else "#34495e")
        ax.errorbar(
            r["mrr"], y,
            xerr=[[r["mrr"] - r["mrr_ci"][0]], [r["mrr_ci"][1] - r["mrr"]]],
            fmt="o", color=color, capsize=3,
        )
    ax.set_yticks(ys)
    ax.set_yticklabels([r["name"] for r in rows], fontsize=8.5)
    ax.set_xlabel("MRR (mean over 100 queries, 95% bootstrap CI)")
    ax.set_xlim(0.3, 1.0)
    ax.grid(axis="x", alpha=0.3)
    ax.set_title("Cited-paper ranking: LLM reranking vs. embedding retrieval", fontsize=10)
    fig.tight_layout()
    fig.savefig(OUT / "mrr_ci.svg")
    print((OUT / "results.md").read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()
